def banking_system():
    print("Banking System")
banking_system()
print("Please place your ATM card and enter your account number.")
account=int(input("Enter your account number: "))
password=input("Enter your password:")
amount=int(input("Enter the amount in your account: "))
withdraw=int(input("Enter the amount you want to withdraw: "))
if withdraw<amount:
    print("You have withdrawn rupees",withdraw)
    print("Your remaining balance is",amount-withdraw)
    deposit=int(input("Enter the amount you want to deposit: "))
    if deposit<1000:
      print("MINIMUM DEPOSIT AMOUNT IS 1000")
      print("you have deposited rupees",deposit)
      print("    TRANSACTION DETAILS")
      print("LAST TRANSACTION DATE: 2-4-2026")
      print("LAST TRANSACTION:",deposit)
      print("THANK YOU FOR USING OUR BANKING SYSTEM")
    elif deposit<5000:
      print("DEPOSIT LITTLE MORE FOR YOUR FUTURE")
      print("you have deposited rupees",deposit)
      print("Your remaining balance is",amount-withdraw+deposit)
      print("Transaction successful")
      print("    TRANSACTION DETAILS")
      print("TOTAL AMOUNT IN YOUR ACCOUNT",amount)
      print("LAST TRANSACTION DATE: 2-4-2026")
      print("LAST TRANSACTION:",deposit)
      print("THANK YOU FOR BANKING WITH SBI")
    elif deposit>=5000 and deposit<500000:
      print("YOU HAVE SUFFICIENT BALANCE IN YOUR ACCOUNT")
      print("you have deposited rupees",deposit)
      print("Your remaining balance is",amount-withdraw+deposit)
      print("Transaction successful")
      print("    TRANSACTION DETAILS")
      print("TOTAL AMOUNT IN YOUR ACCOUNT",amount)
      print("LAST TRANSACTION DATE: 2-4-2026")
      print("LAST TRANSACTION:",deposit)
      print("THANK YOU FOR BANKING WITH SBI")
    elif deposit>=500000:
      print("HURRAY!HIGH SAVINGS IN YOUR ACCOUNT")
      print("you have deposited rupees",deposit)
      print("Your remaining balance is",amount-withdraw+deposit)
      print("Transaction successful")
      print("    TRANSACTION DETAILS")
      print("TOTAL AMOUNT IN YOUR ACCOUNT",amount)
      print("LAST TRANSACTION DATE: 2-4-2026")
      print("LAST TRANSACTION:",deposit)
      print("THANK YOU FOR BANKING WITH SBI")   
    else:
      print("Invalid amount")
     
else:
    print("Insufficient balance")
