print("BIODATA RUNTIME")
name=input("Name: ")
age=int(input("Age: "))
DOB=input("date of birth: ")
mothername=input("Mother's name : ")
fathername=input("Father's name: ")
education=input("Educational qualification : ")
hobby=input("Hobbies: ")
percentage10th=float(input("10th percentage : "))
knownlanguages=input("Languages known: ")
email=input("Email ID : ")
phoneno=int(input("Phone number: "))